#!/usr/bin/env python3

# Copyright 2024 HHCM, Istituto Italiano di Tecnologia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import rclpy
from nicla_vision_ros2_py import TFOnImage


def main(args=None):

    rclpy.init(args=args)
    tf_on_image_node = TFOnImage(rate=100)

    try:
        rclpy.spin(tf_on_image_node)

    except Exception as e:
        tf_on_image_node.get_logger().error("Exception: %s" % str(e))

    tf_on_image_node.stop()
    tf_on_image_node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()